### ISSUE TITLE
Help using verifyJWT()

### ISSUE THREAD

**Issue by oliviervaillancourt** [kjur/jsrsasign#122] opened 2015-10-02 19:44 UTC
(not really an issue, but I have a question)
Hi,

I'm trying to verify a JWT token with your Library (I managed to decode the token) but I'm not able to verify the token.

Basically, I have my signature in a base64 encoded string and I'm wondering how to convert it so that it works with verifyJWT().  I understand I need to convert to hex but I've tried a couple of things and not able to make it work.

I can provide example JWT and base64 signature if required.

arigato
Olivier

**Comment by kjur** [comment] 2015-10-03 01:47
Hi @oliviervaillancourt , could you provide your JWT and public key or password to verify which is raising issue? Thanks.

**Comment by oliviervaillancourt** [comment] 2015-10-05 20:41
Hi @kjur,

I apologize for the delay, I missed the notification about your reply.  Here's en example of JWT token and the secret.  Note that the secret is in base64.  Also, these are from a testing environment, so no worries.  I've validated them on jwt.io

Thanks

TOKEN

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImV4dGFwcHN2Y3VzciIsImVtYWlsIjoib2xpdmllci52YWlsbGFuY291cnQrc2hvdWxkbm9iZXVzZWRAZ21haWwuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzc3YTE1OGZjY2JlZmIyMmU1NjYyNzVhYzVjNTdiZmFlP3M9NDgwXHUwMDI2cj1wZ1x1MDAyNmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmV4LnBuZyIsIm5pY2tuYW1lIjoiZXh0YXBwc3ZjdXNyIiwibmFtZSI6Im9saXZpZXIudmFpbGxhbmNvdXJ0K3Nob3VsZG5vYmV1c2VkQGdtYWlsLmNvbSIsIkF1dGhvcml6YXRpb25TZXJ2aWNlVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKbGJXRnBiQ0k2SW1WNGRHRndjSE4yWTNWemNpSXNJbWxoZENJNk1UUTBOREEzTnpReE15d2laWGh3SWpveE5EUTBNRGM0TURFekxDSmhkV1FpT2lKdFJVRm5VM1JyZVVKRE5qZHpVMkpUYUVsS1RUVnRSVFp3Y2pkNlZVbEpTeUlzSW1semN5STZJbmR2Ym1SbGNuZGhjbVV1WVhWMGFEQXVZMjl0SWl3aWMzVmlJam9pYjJ4cGRtbGxjaTUyWVdsc2JHRnVZMjkxY25RcmMyaHZkV3hrYm05aVpYVnpaV1JBWjIxaGFXd3VZMjl0SW4wLmlmM1FnejdwaGVBVWVLRGx3ay1TQkhRNDhUWkxwTno0U0EtclM5NXZxaUUiLCJ0ZW5hbnRpZCI6ImNhc3BlckpTVGVzdFRlbmFudCIsIlJvbGVzIjpbIkNVU1RPTUVSIiwiVVNFUiJdLCJfaWQiOiIwZTg3NzY5YWQ1MjA5ZGQ4MDAxOGVjMTc1Y2YwMmYyYyIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImNsaWVudElEIjoibUVBZ1N0a3lCQzY3c1NiU2hJSk01bUU2cHI3elVJSUsiLCJ1c2VyX2lkIjoiYXV0aDB8NTYwZWEwODE2NGFiNTc0ODZjYTQ1NDU0IiwiaWRlbnRpdGllcyI6IntcInVzZXJfaWRcIjpcIjU2MGVhMDgxNjRhYjU3NDg2Y2E0NTQ1NFwiLFwicHJvdmlkZXJcIjpcImF1dGgwXCIsXCJjb25uZWN0aW9uXCI6XCJBdXRoMC1TZXJ2aWNlMlNlcnZpY2UtU3RvcmUtRm9yLURldlwiLFwiaXNTb2NpYWxcIjpmYWxzZX0iLCJ1cGRhdGVkX2F0IjoiMjAxNS0xMC0wNVQyMDozNjo1Mi45MTVaIiwiY3JlYXRlZF9hdCI6IjIwMTUtMTAtMDJUMTU6MTk6MjkuNjA0WiIsImdsb2JhbF9jbGllbnRfaWQiOiJJWUVYdlN6dmhTYXJxMDZkeXdYejN6YzR2WVh0dWdrOCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2Nhc3BlckpTVGVzdFRlbmFudC8iLCJzdWIiOiJhdXRoMHw1NjBlYTA4MTY0YWI1NzQ4NmNhNDU0NTQiLCJhdWQiOiJodHRwczovL25jaGljY29udGVudHNlcnZlci5jbG91ZGFwcC5uZXQiLCJleHAiOjE0NDQwNzc0NzQsImlhdCI6IjE0NDQwNzc0MTMiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJ0aWQiOiJjYXNwZXJKU1Rlc3RUZW5hbnQiLCJuYmYiOjE0NDQwNzc0MTR9.q40gYgoQeO99wuJaHay8LZ2zh9YuErc4_ny8-zgxbhk

SECRET

ZXC5C417E1462E247D999F396B21FD3C6C9=

**Comment by kjur** [comment] 2015-10-06 02:39
Hi @oliviervaillancourt , I've confirmed that above JWT is failed to verify by latest jsrsasign but it is valid by jwt.io site. For jsrsasign, a base64 password can be converted into a hexadecimal string by b64tohex function defined in ext/base64.js. I need to further investigation. Thanks.

**Comment by kjur** [comment] 2015-10-06 22:53
Hi @olivervaillancourt , currently still under investigation but I'll share what I found with you.

- I've developped small tool to verify JWS signature by OpenSSL dgst hmac command.
- Your signature is valid by above tool.
- I found CryptoJS Mac API generates wrong mac code for your signature.
- The jwt.io site is using my old version of jsrsasign 4.1.8 and it verifies your signature correctly.
- Your base64 pass code is correctly passed to jsrsasign API.

It seems that large mac signed data or binary password may raise this issue. That's the current status. Thanks.

**Comment by oliviervaillancourt** [comment] 2015-10-07 00:35
Kenji, I appreciated your help very much.  Thanks for the frequent update.

Arigato

**Comment by kjur** [comment] 2015-10-11 05:34
Hi, I found the cause of issue and fix it. Then I'm writing test codes and document update. I hope it will be released in a few days.

**Comment by kjur** [comment] 2015-10-11 05:41
With respect to CryptoJS manual, CryptoJS Hmac accepts only a hexadecimal string as mac password. However it will generate wrong mac signature in some case. Thus all type of password argument will be converted into CryptoJS DWord internally, then applyed to CryptoJS Hmac for its workaround.

**Comment by kjur** [comment] 2015-10-12 06:30
I've fixed the issue and released 4.10.0 today. Thanks.
https://github.com/kjur/jsrsasign/releases/tag/4.10.0

**Comment by oliviervaillancourt** [comment] 2015-10-12 12:07
Hi Kenji,

Very appreciated,  I will test it out soon

Confirmation:  I need to convert my base64 key to hex to verify the token
signature, I can't pass base64 to the method directly?

Arigato gozaimas (hope I have the spelling right)

**Comment by kjur** [comment] 2015-10-12 12:31
Hi @oliviervaillancourt , latest version doesn't require any key conversion.

SYNTAX
KJUR.jws.JWS.verify(*JWSSIGNATURE*, {b64: *BASE64MACKEY*}, [*ACCEPTABLEALGS*]);
EXAMPLE
isValid = KJUR.jws.JWS.verify('eyJh...', {b64: 'Mi/ab8...a=='}, ['HS256']);

See below in detail:
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verify

BTW, you spelling is correct :)

Thanks.

**Comment by oliviervaillancourt** [comment] 2015-10-13 14:22
Hi Kenji,

I've tried 4.10.0 this morning.  Maybe I'm doing something wrong but I have issues with using the verify method with the ```{b64: 'signature'}``` second param.

If I run this:
```javascript
token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImV4dGFwcHN2Y3VzciIsImVtYWlsIjoib2xpdmllci52YWlsbGFuY291cnQrc2hvdWxkbm9iZXVzZWRAZ21haWwuY29tIiwidXBkYXRlZF9hdCI6IjIwMTUtMTAtMTNUMTM6NDU6MDMuNTM4WiIsImNyZWF0ZWRfYXQiOiIyMDE1LTEwLTAyVDE1OjE5OjI5LjYwNFoiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9jYXNwZXJKU1Rlc3RUZW5hbnQvIiwiYXVkIjoiRkFLRSBOQ0ggbm90IHVzZWQiLCJleHAiOjE0NDQ4MzAzMDQsImlhdCI6IjE0NDQ3NDM5MDQiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJ0ZW5hbnRpZCI6ImNhc3BlckpTVGVzdFRlbmFudCIsIm5iZiI6MTQ0NDc0MzkwNH0.DA37pmUEghQTM-mADrgmUTHpKSbsAAXeItdwMJLDXOg';
    signature = 'YXNkZg==';
    //signature = 'YXNkZjI=';
    var isValid = KJUR.jws.JWS.verify(token, { b64: signature }, ['HS256']);
```
I get this:

    type: uncaughtError
    file: Tests\AuthenticationTests.js:288
    error: 'undefined' is not a function (evaluating 't.match(/^[0-9A-Fa-f]+/)')
           TypeError: 'undefined' is not a function (evaluating 't.match(/^[0-9A-Fa-f]+/)')
               at C:/Workspace2/EMI Program/Dev/Source/WonderwareOnline/ContentServer2/ContentServer.FunctionalTests/extModules/jsrsasign/lib/jsrsasign.js:288

Looking at jws-3.3.js line 399+, if we skip this if, it seems to work.  Also, in the case of b64 object, the flow enters this if and fails in ```.match()```.

```javascript
if (typeof key != "string" &&
400 	    key.length != 0 &&
401 	    key.length % 2 != 0 &&
402 	    ! key.match(/^[0-9A-Fa-f]+/)) {
403 	    throw "key shall be a hexadecimal str for HS* algs";
404 	}
```
Is this expected, am I doing something wrong?

Thanks

**Comment by kjur** [comment] 2015-10-13 15:02
Hi @oliviervaillancourt , you are right. Those lines shall be removed. I'll fix it in the next version. Thanks.

**Comment by oliviervaillancourt** [comment] 2015-10-13 15:05
Great, Thanks.

**Comment by kjur** [comment] 2015-10-13 21:37
Hi @oliviervaillancourt , I've fixed it on latest version 5.0.0 released today. Thanks.

**Closed by kjur** 2015-10-13 21:37 UTC
Labels: bug

**Comment by oliviervaillancourt** [comment] 2015-10-14 13:28
Hi Kenji,

Pleased to report that it's all good now.

Thanks for your quick action on this matter, Very much appreciated.

Olivier

**Comment by ChaosCrafter** [comment] 2020-11-19 04:38
Hi @kjur,
I'm not sure if I'm on the right track or not.
We use your library but we are now looking at supporting several issuers, each with different keys.
We expect each one to be compliant with the openid JWKSet approach (/.well-known/openid-configuration, and /.well-known/openid-configuration/jwks)

My ideal would be to perform a verifyJWT, and have it lookup the keys by openid, so I just have to state which iss values are valid.  If not that then it becomes more messy as I have to parse the token to get the source, fetch the openid-configuration, lookup the jwks target, fetch that, convert the key to a format compatible with verifyJWT, and finally perform the verification.

Have I overlooked some nice function I can call that does it all?  or could you point me at an example that handles multiple iss sources and the different JWKS key data for each?

Or have I missed something fundamental and I'm doing it all wrong?
