### ISSUE TITLE
Error "this.n is undefined" when verifying signature

### ISSUE THREAD

**Issue by beamerblvd** [kjur/jsrsasign#46] opened 2013-12-13 00:22 UTC
I have the following code:

```javascript
var signer = new KJUR.crypto.Signature({ 'alg': 'SHA1withRSA', 'prov': 'cryptojs/jsrsa' });
signer.initVerifyByCertificatePEM('-----BEGIN PUBLIC KEY-----\n' +
'MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALvU5TrNPuQ8bgZp0ou+PvKqTpZJ6lS6\n' +
'WpNOkIt2hncaHBpPFxCU3h1Y+sXtaY1mqZC30yj6q4KHZAwcuN9R3BMCAwEAAQ==\n' +
'-----END PUBLIC KEY-----');
signer.updateString('Some string hello world.');
if(!signer.verify(signature))
	alert('Signature Invalid!');
```

(Note that this is a 512-bit key.) This conforms to the example in the [tutorial](https://github.com/kjur/jsrsasign/wiki/Tutorial-for-Signature-class). The code works fine up until the point it calls `signer.verify(signature)`. Then I get the error "this.n is undefined."

I traced it down to the fact that `initVerifyByCertificatePEM` sets the public key to an `x509`, which has no `n` property. Calling `verify` ultimately attempts to use the `n` property, but `n` is only present in `RSAKey`. I can set the public key to an `RSAKey` by calling `initVerifyByPublicKey` (instead of `initVerifyByCertificatePEM`) but that presents another problem: You can't create an `RSAKey` with just the encoded public key. You have to have the private key.

Since I'm just testing this right now and have access to private key, this is OK. I can successfully verify the signature as long as I have the private key `RSAKey`. But there doesn't appear to be a way to verify a signature with just the encoded public key string available.

**Comment by unicorndreams** [comment] 2015-02-19 14:53
I got the same error on the "sample-rsasign.html" file. Everything runs fine, until you change the public certificate (either entering a PKCS#8 one or just deleting one random character from the default one). The error looks like this:

TypeError: this.n is undefined
rsasign-1.2.js (line 267, col 8): if (biSig.bitLength() > this.n.bitLength()) return 0;

Version 1.0 of "rsa-sign.js" works fine (even on PKCS#8 pairs), as it doesn't have that IF statement. Knocking it out makes it work again for "similar" certificates (changing some characters that do not encode the actual key), but anything else makes it break somewhere else:

TypeError: m is undefined
jsbn.js (line 529): if(e < 256 || m.isEven()) z = new Classic(m); else z = new Montgomery(m);

Unfortunately, I don't have time now to track down the error, but the bug is definitely there.

**Comment by kjur** [comment] 2015-09-15 14:16
I couldn't reproduce your errors. Now "sample-rsasign.html" works fine. Sorry but I'll close this ticket.

**Closed by kjur** 2015-09-15 14:16 UTC
