### ISSUE TITLE
Moving EC Keys Into BouncyCastle

### ISSUE THREAD

**Issue by BlueMeanie** [kjur/jsrsasign#44] opened 2013-12-04 20:40 UTC
Hello,

I need to be able to move EC Keys between this Javascript Library and BouncyCastle APIs.  I'm a bit confused as to what format the basic JS functionality generates and how to reconstitute them in Java(and vice versa).

for instance to build a Public Key in bouncy castle I take a hex string via 

> keypair = ec.generateKeyPairHex();
> prvkey = keypair.ecprvhex;

byte[] publicKeyFromJSArray = Hex.decodeHex(publicKeyHexFromJavascript.toCharArray());  // this is the prvkey String

```
    ECPoint pubPoint = ecSpec.getCurve().decodePoint(publicKeyFromJSArray);
    org.bouncycastle.jce.spec.ECPublicKeySpec pubKeySpec2 = new ECPublicKeySpec(  pubPoint,
             ecSpec); 
    PublicKey pubkey2 = fact.generatePublic(pubKeySpec2);
```

I later attempt to make a signature with it and it fails.  Any idea how to do this?

thanks!  -bm

**Comment by Ruffio** [comment] 2017-07-25 07:46
@BlueMeanie has this 'issue' been resolved? It looks like it was a question about implementation and not a bug/issue. Please consider to close it. Thanks.

**Comment by Ruffio** [comment] 2017-08-27 05:38
@kjur this question should be closed due to lack of response from originator

**Comment by kjur** [comment] 2017-09-10 02:40
To share key between Java and jsrsasign, I would recommend to share them in PKCS#8 DER private and public key format. 

For example "prv.p8p.der" is a PKCS#8 DER formatted binary plain EC private key file and
"pub.p8.der" is a PKCS#8 DER formatted binary EC public key file.

Then to load private key in Java:
```Java
byte[] prvKeyBytes = loadBytes("../prv.p8p.der");
KeyFactory kf = KeyFactory.getInstance("EC");
KeySpec keySpec = new PKCS8EncodedKeySpec(prvKeyBytes);
PrivateKey prvKey = kf.generatePrivate(keySpec);
```

To load public key in Java:
```Java
byte[] pubKeyBytes = loadBytes("../pub.p8.der");
KeyFactory kf = KeyFactory.getInstance("EC");
KeySpec keySpec = new X509EncodedKeySpec(certBytes);
PublicKey pubKey = kf.generatePublic(keySpec);
```

To load private key in JavaScript with jsrsasign:
```JavaScript
rs = require("jsrsasign");
rsu = require("jsrsasign-util");
hPrv = rsu.readFileHexBin("prv.p8p.der");
prvkey = rs.KEYUTIL.getKey(hPrv, "pkcs8rv");
```

To load public key in JavaScript with jsrsasign:
```JavaScript
rs = require("jsrsasign");
rsu = require("jsrsasign-util");
hPub = rsu.readFileHexBin("pub.p8.der");
pubkey = rs.KEYUTIL.getKey(hPub, "pkcs8pub");
```

**Closed by kjur** 2017-09-10 02:40 UTC
Labels: question
